ActPlat/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'', include('activity_platform.urls')),
]

activity_platform/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.activity_list, name='activity_list'),
    url(r'^activity_mine/$', views.activity_mine, name='activity_mine'),
	url(r'^activity/(?P<pk>\d+)/$', views.activity_detail, name='activity_detail'),
	url(r'^about', views.activity_about, name='activity_about'),
	url(r'^accounts/login/$',views.login),
	url(r'^accounts/logout/$',views.logout),
	url(r'^accounts/register/$',views.register),
	url(r'^add_new/$',views.add_new),
]

activity_platform/models.py
from django.db import models
from django.utils import timezone


from django.db import models
from django.utils import timezone

class Post(models.Model):
    活動名稱 = models.CharField(default="建議最多十四字", max_length=15)
    副標題 = models.CharField(default="建議最多二十五字", blank=True, max_length=30)
    #圖片 = models.TextField(default=".jpg")
    圖片 = models.ImageField(default="back.png", upload_to='upload/')
    簡介 = models.TextField(default="簡介你的活動(建議最多三百二十五字)", max_length=1000)
    開始日期與時間 = models.DateTimeField(blank=True, null=True)
    結束日期與時間 = models.DateTimeField()
    地點 = models.CharField(blank=True, max_length=200)
    對象 = models.TextField(blank=True, max_length=200)
    費用 = models.CharField(blank=True, max_length=200)
    人數限制 = models.TextField(blank=True, max_length=200)
    報名死線 = models.DateTimeField(blank=True, null=True)
    聯絡資訊 = models.TextField(default="例如活動專頁等")
    類型 = models.CharField(max_length=200,blank=True)
    標籤 = models.CharField(max_length=200,blank=True)
    詳細地點 = models.TextField(max_length=200,blank=True)
    詳細費用 = models.TextField(max_length=200,blank=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.活動名稱
		
class Like(models.Model):
    user = models.CharField(max_length=20, blank=True)
    #user = models.ManyToManyField(User)
    post = models.ManyToManyField(Post)
    
    def __str__(self):
        return self.user

activity_platform/forms.py
from django import forms

class Add_new(forms.Form):
    活動名稱 = forms.CharField(max_length=15)
    活動副標題 = forms.CharField(max_length=30)
    圖片=forms.ImageField(required=False)
    開始日期與時間 = forms.DateTimeField(input_formats=["%Y-%m-%dT%H:%M"])
    結束日期與時間 = forms.DateTimeField(input_formats=["%Y-%m-%dT%H:%M"])
    簡單地點 = forms.CharField(max_length=200)
    簡單費用 = forms.CharField(max_length=200)
    報名截止日期與時間 = forms.DateTimeField(required=False, input_formats=["%Y-%m-%dT%H:%M"])
    簡介 = forms.CharField(max_length=1000)
    詳細地點 = forms.CharField(max_length=200)
    詳細費用 = forms.CharField(max_length=200)
    活動對象 = forms.CharField(max_length=200)
    人數限制 = forms.CharField(max_length=200)
    聯絡資訊 = forms.CharField()
    性質 = forms.CharField(max_length=200)
    類型 = forms.CharField(max_length=200)
    費用分類 = forms.CharField(max_length=200)
    活動對象分類 = forms.CharField(max_length=200)

activity_platform/views.py
from .models import Post, Like
from .forms import Add_new
from django.utils import timezone
from django.shortcuts import render, render_to_response, HttpResponse, HttpResponseRedirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth

# Create your views here.
def activity_list(request):
    posts = Post.objects.filter(結束日期與時間__gte=timezone.now()).order_by('開始日期與時間')
    if request.method == "POST":
        if not request.user.is_authenticated():
            return HttpResponseRedirect('/accounts/login/')
        else:
            return render(request, 'activity_platform/activity_list.html',locals())
    
    else:
        return render(request, 'activity_platform/activity_list.html',locals())
		
def activity_mine(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/accounts/login/')
    else:
        user = request.user.username
        posts = Like.objects.get(user=user).post.all()
        return render(request, 'activity_platform/activity_mine.html',locals())		

def activity_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        if not request.user.is_authenticated():
            return HttpResponseRedirect('/accounts/login/')
        else:
            
            #post = Post.objects.get(id=request.POST['id'])
            user = request.user.username
            
            if not Like.objects.filter(user=user):
                Like.objects.create(user=user).post.add(post)
            else:
                #return HttpResponse(Like.objects.get(user=user).restaurant.all())
                
                if post not in Like.objects.get(user=user).post.all():
                    Like.objects.get(user=user).post.add(post)
                else:
                    Like.objects.get(user=user).post.remove(post)
            allpost = Like.objects.get(user=user).post.all()
            return render(request, 'activity_platform/activity_detail.html',locals())
    else:
        if not request.user.is_authenticated():
            return render(request, 'activity_platform/activity_detail.html', {'post': post})
        else:
            user = request.user.username
            if not Like.objects.filter(user=user):
                return render(request, 'activity_platform/activity_detail.html', locals())
            else:
                allpost = Like.objects.get(user=user).post.all()
                return render(request, 'activity_platform/activity_detail.html', locals())
    
	
def activity_about(request):
    return render(request, 'activity_platform/activity_about.html', {})
	
def login(request):
    if request.user.is_authenticated(): 
        return HttpResponseRedirect('/')

    error = False
    
    if request.method == "POST":
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
    
        user = auth.authenticate(username=username, password=password)
    
        if user is not None and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect('/')
        else:
            error = True
            return render(request, 'activity_platform/login.html', locals())
    else:
        return render(request, 'activity_platform/login.html', locals())
		
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return HttpResponseRedirect('/accounts/login/')
    else:
        form = UserCreationForm()
    return render(request, 'activity_platform/register.html',locals())

def add_new(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/accounts/login/')
    else:
        if request.method == 'POST':
            errors = False
            f = Add_new(request.POST, request.FILES)
            if f.is_valid():
                活動名稱 = f.cleaned_data['活動名稱']
                副標題 = f.cleaned_data['活動副標題']
                圖片 = f.cleaned_data['圖片']
                簡介 = f.cleaned_data['簡介']
                開始日期與時間 = f.cleaned_data['開始日期與時間']
                結束日期與時間 = f.cleaned_data['結束日期與時間']
                地點 = f.cleaned_data['簡單地點']
                對象 = f.cleaned_data['活動對象']
                費用 = f.cleaned_data['簡單費用']
                人數限制 = f.cleaned_data['人數限制']
                報名死線 = f.cleaned_data['報名截止日期與時間']
                聯絡資訊 = f.cleaned_data['聯絡資訊']
                類型 = f.cleaned_data['類型']
                標籤 = f.cleaned_data['性質']+" "+f.cleaned_data['類型']+" "+f.cleaned_data['費用分類']+" "+f.cleaned_data['活動對象分類']
                詳細地點 = f.cleaned_data['詳細地點']
                詳細費用 = f.cleaned_data['詳細費用']
 
                Post.objects.create(活動名稱=活動名稱, 副標題=副標題, 圖片=圖片, 簡介=簡介, 開始日期與時間=開始日期與時間, 結束日期與時間=結束日期與時間, 地點=地點, 對象=對象, 費用=費用, 人數限制=人數限制, 報名死線=報名死線, 聯絡資訊=聯絡資訊, 類型=類型, 標籤=標籤, 詳細地點=詳細地點, 詳細費用=詳細費用)
			
                return HttpResponseRedirect('/')
            else:
                errors = True
                return render(request, 'activity_platform/add_new.html',locals())
        else:
            return render(request, 'activity_platform/add_new.html',locals())

activity_platform/templates/activity_platform/activity_detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="keywords" content="網頁關鍵字">	
<title>ActPlat - {{ post.活動名稱 }}</title>
<link rel="SHORTCUT ICON" href={% static 'image/just_logo.png' %}>

<script src="https://use.fontawesome.com/9ed2b9813e.js"></script>
<link rel="stylesheet" href= {% static 'css/activity_detail.css' %} type="text/css" />
<script type="text/javascript" src={% static 'js/jquery-3.1.1.min.js' %}></script>
<script type="text/javascript" src={% static 'js/jquery.color-2.1.2.js' %}></script>
<script type="text/javascript" src={% static 'js/menu2.js' %}></script>
<script type="text/javascript" src={% static 'js/scroll.js' %}></script>
<script type="text/javascript" src={% static 'js/replace.js' %}></script>
<script type="text/javascript" src={% static 'js/hover.js' %}></script>
</head>


<body>
<div id="head">
	<ul>
		<li><span class = "option1">活動名稱</span></li>
		<li><span class = "option2">活動簡介</span></li>
		<li><span class = "option3">基本資訊</span></li>
		<li><span class = "option4">聯絡資訊</span></li>
	</ul>
	<div class = "arrow-up"></div>
	<div class = "arrow-up2"></div>
</div>

<div id="container">
	<div class="p1">
		<div class="title">
			<div class="title_image" style="background-image: url({% static 'image/' %}{{ post.圖片 }});background-size: 100%;background-position: center;"><img src={% static 'image/back.png' %}></div>
			<div class="title_text">{{ post.活動名稱 }}</div>
			<div class="title_subtext">{{ post.副標題 }}</div>
			<div class="title_line"></div>
			<div class="title_date">{{ post.開始日期與時間|date:"Y . m . d" }}</div>
		
					<form action="#" method="post">
						
						{% csrf_token %}
						{% if post in allpost %}
						
						<input class="submit" type="submit" name={{ post.id }} value="取消收藏">
						<div class="heart">{{ post.like_set.all|length }}<i class="fa fa-heart" aria-hidden="true"></i></div>
						{% else %}
						
						<input class="submit" type="submit" name={{ post.id }} value="我要收藏">
						<div class="heart">{{ post.like_set.all|length }}<i class="fa fa-heart-o" aria-hidden="true"></i></div>
						{% endif %}
					</form>
		
		</div>
					
	</div>
	<div class="p2">
		<div class="brief_title">簡介</div>
		<div class="brief_line"></div>
		
		{% autoescape off %}
		<div class="brief_text">
			{{ post.簡介|linebreaksbr }}
		</div>
		{% endautoescape %}
	</div>
	<div class="p3">
	
	<div class="wrapper">
	{% autoescape off %}
		<div class="info">
			<div class="icon"><i class="fa fa-calendar-o" aria-hidden="true"></i></div>
			<div class="info_title">活 動 日 期</div>
			<div class="info_line"></div>
			<div class="text_date">
				<div class="start_date">{{ post.開始日期與時間|date:"Y.m.d (D) H:i" }}</div>
				<div>|</div>
				<div class="end_date">{{ post.結束日期與時間|date:"Y.m.d (D) H:i" }}</div>
			</div>
		</div>
		<div class="info">
			<div class="icon"><i class="fa fa-map-marker"></i></div>
			<div class="info_title">活 動 地 點</div>
			<div class="info_line"></div>
			<div class="text_location">{{ post.詳細地點|linebreaksbr }}</div>
		</div>
		<div class="info">
			<div class="icon"><i class="fa fa-usd" aria-hidden="true"></i></div>
			<div class="info_title">活 動 費 用</div>
			<div class="info_line"></div>
			<div class="text_fee">{{ post.詳細費用|linebreaksbr }}</div>
		</div>
		<div class="info">
			<div class="icon"><i class="fa fa-user" aria-hidden="true"></i></div>
			<div class="info_title">活 動 對 象</div>
			<div class="info_line"></div>
			<div class="text_for">{{ post.對象 }}</div>
		</div>
		<div class="add_info">
			<div class="limit">
				人 數 限 制&emsp;|&emsp;{{ post.人數限制 }}
			</div>
			<div class="deadline">
				報 名 截 止&emsp;|&emsp;<span>{{ post.報名死線|date:"m/d H:i" }}</span>
			</div>
		</div>
	{% endautoescape %}
	</div>
	
	</div>
	<div class="p4">
		<a href="{{ post.聯絡資訊 }}" target="_blank"><div class="more"><i class="fa fa-info-circle"></i></div></a>
		
		<div id="footer">
			<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSewtGW6lKVvS1dvGQ-m54w1GTy6TN6BDE_JF2FXnutTS38OZg/viewform">
				<div id="icon_contact"><i class="fa fa-envelope-o" aria-hidden="true"></i><div id="contact">給點回饋</div></div>
			</a>
			<a href="/add_new/">
				<div id="icon_contact"><i class="fa fa-bullseye" aria-hidden="true"></i><div id="contact">我要宣傳</div></div>
			</a>
			<a target="_blank" href="https://www.facebook.com/ActPlat">
				<div id="icon_contact"><i class="fa fa-facebook-square" aria-hidden="true"></i><div id="contact">臉書專頁</div></div>
			</a>
			<a target="_blank" href="{% url 'activity_about' %}">
				<div id="icon_contact"><i class="fa fa-question" aria-hidden="true"></i><div id="contact">關於我們</div></div>
			</a>
			<a href="/">
				<div id="icon_contact"><i class="fa fa-home" aria-hidden="true"></i><div id="contact">網站首頁</div></div>
			</a>
		</div>	
		
	</div>
<!--container--></div>


</body>
</html>

activity_platform/templates/activity_platform/activity_list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="keywords" content="網頁關鍵字">	
<title>ActPlat - 首頁</title>
<link rel="SHORTCUT ICON" href={% static 'image/just_logo.png' %}>

<script src="https://use.fontawesome.com/f4d3a939e1.js"></script>
<link rel="stylesheet" href={% static 'css/activity_list.css' %} type="text/css" />
<script type="text/javascript" src={% static 'js/jquery-3.1.1.min.js' %}></script>
<script type="text/javascript" src={% static 'js/ellipsis.js' %}></script>
<script type="text/javascript" src={% static 'js/godown.js' %}></script>
<script type="text/javascript" src={% static 'js/loading.js' %}></script>
<script type="text/javascript" src={% static 'js/menu.js' %}></script>
<script type="text/javascript" src={% static 'js/replace.js' %}></script>
<script type="text/javascript" src={% static 'js/hover.js' %}></script>

</head>


<body>
<div id="intro">
<script src={% static 'js/particles.js' %}></script>
<script src={% static 'js/app.js' %}></script>
<div id="notification">
	<div id="lastupdate"><span>上次更新|&nbsp;</span><br>
		&emsp;&emsp;&emsp;&emsp;&emsp;2017.05.01 20:00<br>
	</div>
	<div id="whatsnew"><span>新增功能|&nbsp;</span><br>
		&emsp;&emsp;&emsp;&emsp;&emsp;篩選活動<br>
		&emsp;&emsp;&emsp;&emsp;&emsp;活動簡介<br>
		&emsp;&emsp;&emsp;&emsp;&emsp;可以自己宣傳活動囉<br>
		&emsp;&emsp;&emsp;&emsp;&emsp;登入後可以收藏活動<br>
		&emsp;&emsp;&emsp;&emsp;&emsp;看到各活動的收藏數<br>
	</div>
	<div id="todo"><span>預計功能|&nbsp;</span><br>
		&emsp;&emsp;&emsp;&emsp;&emsp;手機板網頁<br>
		&emsp;&emsp;&emsp;&emsp;&emsp;排序方式<br>
		&emsp;&emsp;&emsp;&emsp;&emsp;搜尋功能<br>
		&emsp;&emsp;&emsp;&emsp;&emsp;時間軸<br>
	</div>
</div>
<div id="loader"></div>
<div id="welcome"><img src={% static 'image/logo.png' %}></div>
<div><img id="godown" src={% static 'image/down_arrow.png' %}></div>
</div>

<div id="head">
	<ul>
		<!--<li class = "option">活動時間
			<ul class = "selection">
				<li id = "1.1"><div id="selection_text">a</div><div id="slider"><div id="switch"></div></div></li>
				<li id = "1.2"><div id="selection_text">b</div><div id="slider"><div id="switch"></div></div></li>
				<li id = "1.3"><div id="selection_text">c</div><div id="slider"><div id="switch"></div></div></li>
				<li id = "1.4"><div id="selection_text">d</div><div id="slider"><div id="switch"></div></div></li>
			</ul>
		</li>-->
		<li class = "option">類型
			<ul class = "selection">
				<li id = "2.1"><div id="selection_text">學校活動</div><div id="slider"><div id="switch"></div></div></li>
				<li id = "2.2"><div id="selection_text">學生會</div><div id="slider"><div id="switch"></div></div></li>
				<li id = "2.3"><div id="selection_text">系學會</div><div id="slider"><div id="switch"></div></div></li>
				<li id = "2.4"><div id="selection_text">社團活動</div><div id="slider"><div id="switch"></div></div></li>
				<li id = "2.5"><div id="selection_text">其他</div><div id="slider"><div id="switch"></div></div></li>
			</ul>
		</li>
		<li class = "option">性質
			<ul class = "selection">
				<li id = "3.1"><div id="selection_text">室內．學術</div><div id="slider"><div id="switch"></li>
				<li id = "3.2"><div id="selection_text">室內．休閒</div><div id="slider"><div id="switch"></li>
				<li id = "3.3"><div id="selection_text">戶外．運動</div><div id="slider"><div id="switch"></li>
				<li id = "3.4"><div id="selection_text">戶外．休閒</div><div id="slider"><div id="switch"></li>
				<li id = "3.5"><div id="selection_text">其他</div><div id="slider"><div id="switch"></li>
			</ul>
		</li>
		<li class = "option">費用
			<ul class = "selection">
				<li id = "4.1"><div id="selection_text">免費且備餐</div><div id="slider"><div id="switch"></li>
				<li id = "4.2"><div id="selection_text">免費</div><div id="slider"><div id="switch"></li>
				<li id = "4.3"><div id="selection_text">0-100元</div><div id="slider"><div id="switch"></li>
				<li id = "4.4"><div id="selection_text">101-500元</div><div id="slider"><div id="switch"></li>
				<li id = "4.5"><div id="selection_text">500元以上</div><div id="slider"><div id="switch"></div></div></li>
			</ul>
		</li>
		<li class = "option">對象
			<ul class = "selection">
				<li id = "5.1"><div id="selection_text">不限</div><div id="slider"><div id="switch"></li>
				<li id = "5.2"><div id="selection_text">校內學生</div><div id="slider"><div id="switch"></li>
				<li id = "5.3"><div id="selection_text">系內限定</div><div id="slider"><div id="switch"></li>
				<li id = "5.4"><div id="selection_text">社團限定</div><div id="slider"><div id="switch"></li>
			</ul>
		</li>

	</ul>
	<ul class="right">
		{% if request.user.is_authenticated %}
        <li class = "option">哈囉~{{request.user}}
			<ul class = "selection">
				<a href="/activity_mine/"><li><div id="selection_text">我收藏的活動</div></li></a>
				<a href="/accounts/logout/"><li><div id="selection_text">登出</div></li></a>
		</li>
        
        {% else %}
        <li class = "option">登入/註冊
			<ul class = "selection">
				<a href="/accounts/login/"><li><div id="selection_text">登入</div></li></a>
				<a href="/accounts/register/"><li><div id="selection_text">註冊</div></li></a>
		</li>
        
        {% endif %}
	</ul>
</div>

<div id="container">
	<div id="content">
		<!--
		<div id="block">
			<div class="image"><img src={% static 'image/' %}{{ post.圖片 }}></div>
			<h1>{{ post.活動名稱 }}</h1>
			<div id="brief">{{ post.簡介 }}</div>
			<div id="more_info">
				<p>時間&nbsp;&nbsp;|&nbsp;&nbsp;{{ post.開始日期與時間 }}&nbsp;~&nbsp;{{ post.結束日期與時間 }}<br></p>
				<p>地點&nbsp;&nbsp;|&nbsp;&nbsp;{{ post.地點 }}<br></p>
				<p>報名&nbsp;&nbsp;|&nbsp;&nbsp;{{ post.報名死線 }}<br></p>
				<p>費用&nbsp;&nbsp;|&nbsp;&nbsp;{{ post.費用 }}<br></p>
				<p>對象&nbsp;&nbsp;|&nbsp;&nbsp;{{ post.對象 }}<br></p>
				<p>標籤&nbsp;&nbsp;|&nbsp;&nbsp;OAF<br></p>
			</div>
		</div>
		-->
		{% for post in posts %}
		<a target="_blank" href="{% url 'activity_detail' pk=post.pk %}">
		<div class="{{ post.標籤 }}" id="block">
			<div class="image" style="background-image: url({% static 'image/' %}{{ post.圖片 }});background-size: 100%;background-position: center;"></div>
			<div class="text">
				<div id="title">
					<div id="title_text">{{ post.活動名稱 }}</div>
					<div id="like_count">{{ post.like_set.all|length }}<i class="fa fa-heart-o" aria-hidden="true"></i></div>
					
				</div>
				<div id="time">{{ post.開始日期與時間|date:"Y.m.d (D) H:i" }} ~ {{ post.結束日期與時間|date:"Y.m.d (D) H:i" }}</div>
				<div id="brief">{{ post.簡介 }}</div>
			</div>
			<div id="more_info">
				{% autoescape off %}
				<div id="icon_location"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
				<p id="location">{{ post.地點 }}</p>
				<div id="icon_fee"><i class="fa fa-dollar"></i></div>
				<p id="fee">{{ post.費用 }}</p>
				<div id="icon_deadline"><i class="fa fa-clock-o" aria-hidden="true"></i></div>
				<p id="deadline">{{ post.報名死線|date:"m月d日 H:i截止" }}</p>
				{% endautoescape %}
			</div>
			
		</div>
		</a>
		{% endfor %}
		<!--
		<div id="block">
			<div class="image"><img src={% static 'image/test2.jpg' %}></div>
			<h1>Taipei Hackathon</h1>
			<div id="brief">介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹</div>
			<div id="more_info">
				<p>時間&nbsp;&nbsp;|&nbsp;&nbsp;2017.12.20(日)19:30&nbsp;~&nbsp;2017.12.21(一)05:00<br></p>
				<p>地點&nbsp;&nbsp;|&nbsp;&nbsp;陽明大學音樂前廳<br></p>
				<p>報名&nbsp;&nbsp;|&nbsp;&nbsp;2017.12.20(日)19:30&nbsp;~&nbsp;2017.12.21(一)05:00<br></p>
				<p>費用&nbsp;&nbsp;|&nbsp;&nbsp;100元<br></p>
				<p>對象&nbsp;&nbsp;|&nbsp;&nbsp;陽明大學全體師生<br></p>
				<p>標籤&nbsp;&nbsp;|&nbsp;&nbsp;OAF<br></p>
			</div>
		</div>
		<div id="block">
			<div class="image"><img src={% static 'image/test3.jpg' %}></div>
			<h1>陽明山登山會師</h1>
			<div id="brief">介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹介紹</div>
			<div id="more_info">
				<p>時間&nbsp;&nbsp;|&nbsp;&nbsp;2017.12.20(日)19:30&nbsp;~&nbsp;2017.12.21(一)05:00<br></p>
				<p>地點&nbsp;&nbsp;|&nbsp;&nbsp;陽明大學音樂前廳<br></p>
				<p>報名&nbsp;&nbsp;|&nbsp;&nbsp;2017.12.20(日)19:30&nbsp;~&nbsp;2017.12.21(一)05:00<br></p>
				<p>費用&nbsp;&nbsp;|&nbsp;&nbsp;100元<br></p>
				<p>對象&nbsp;&nbsp;|&nbsp;&nbsp;陽明大學全體師生<br></p>
				<p>標籤&nbsp;&nbsp;|&nbsp;&nbsp;OAF<br></p>
			</div>
		</div>
		<div id="block">
		</div>
		<div id="block">
		</div>
		<div id="block">
		</div>
		<div id="block">
		</div>
		<div id="block">
		</div>
		<div id="block">
		</div>
		<div id="block">
		</div>
		-->
	<!--content--></div>
<!--container--></div>
	<div id="footer">
		<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSewtGW6lKVvS1dvGQ-m54w1GTy6TN6BDE_JF2FXnutTS38OZg/viewform">
			<div id="icon_contact"><i class="fa fa-envelope-o" aria-hidden="true"></i><div id="contact">給點回饋</div></div>
		</a>
		<a href="/add_new/">
			<div id="icon_contact"><i class="fa fa-bullseye" aria-hidden="true"></i><div id="contact">我要宣傳</div></div>
		</a>
		<a target="_blank" href="https://www.facebook.com/ActPlat">
			<div id="icon_contact"><i class="fa fa-facebook-square" aria-hidden="true"></i><div id="contact">臉書專頁</div></div>
		</a>
		<a target="_blank" href="{% url 'activity_about' %}">
			<div id="icon_contact"><i class="fa fa-question" aria-hidden="true"></i><div id="contact">關於我們</div></div>
		</a>
		<a href="/">
			<div id="icon_contact"><i class="fa fa-home" aria-hidden="true"></i><div id="contact">網站首頁</div></div>
		</a>
	</div>	
</body>
</html>